
%% Checar metodo InventarioService/InventarioController - CambiarEstadoDeElemento
%% No seguro de que deberia de enviar para establecer el estado por el que sera cambiado el elemento

classDiagram


    Inventario -- ElementoInventario
    Agenda -- Renta

    InventarioService ..|> InventarioServiceImp : Implementa
    InventarioController -- InventarioService
    InventarioServiceImp -- Inventario
    InventarioServiceImp -- InventarioRepository
    InventarioRepository ..|> InventarioRepositoryImp : Implementa

    AgendaService ..|> AgendaServiceImp : Implementa
    AgendaController -- AgendaService
    AgendaServiceImp -- Agenda
    AgendaServiceImp -- AgendaRepository
    AgendaRepository ..|> AgendaRepositoryImp : Implementa



    class InventarioService{
      <<Interfaz>>
      + obtenerListaDeElementos(elementos : ElementoInventario) ArrayList ElementoInventario
      + crearNuevoElemento(nuevoElemento : ElementoInventario) void
      + eliminarElemento(elementoEliminado : ElementoInventario) void
      + cambiarEstadoDeElemento(elementoCambiado : ElementoInventario) void
      + ReducirAlmacenDeElemento(elementoReducido : ElementoInventario, cantidad : int) void
      + AumentarAlmacenDeElemento(elementoAumentado : ElementoInventario, cantidad : int) void
    
    }

    class AgendaService{
      <<Interfaz>>
      + ObtenerRentas() ArrayList Renta
      + AgregarRenta(RentaNueva : Renta) void
      + EliminarRenta(RentaEliminada : Renta) void
    }

    class InventarioServiceImp{
      - final InventarioRespository inventarioRepository
    }

     class AgendaServiceImp{
      - final AgendaServiceRepository agendaServiceRepository
    }


    class InventarioController{
      + AgregarElementoInventario(nuevoElemento : ElementoInventario) void
      + EliminarElementoInventario(elementoEliminado : ElementoInventario) void
      + ObtenerElementosDeInventario() ArrayList ElementoInventario
      + CambiarEstadoDeElemento(elementoCambiado : ElementoInventario) void
      + ReducirAlmacenDeElemento(reduccion : int) void
      + AumentarAlmacenDeElemento(aumento : int) void
    }

    class AgendaController{
      + ObtenerRentas() ArrayList Renta
      + AgregarRenta(RentaNueva : Renta) void
      + EliminarRenta(RentaEliminada : Renta) void
    }

    class ElementoInventario{
      - m_nombre : String
      - m_categoria : enum
      - m_cantidad : int
      
      + ReducirAlmacen(reduccion : int) void
      + AumentarAlmacen( aumento : int) void
      + Getters()
      + Setters()
    }

    class Inventario{
      - m_elementos : ArrayList ElementoInventario
      + AgregarElemento(nuevoElemento : ElementoInventario) : void
      + EliminarElemento(elementoEliminado : ElementoInventario) : void
      + ObtenerElemento(index : int) : Elemento
      + Getters()
      + Setters()
    }

    class Renta{
      - m_direccion : Direccion
      - m_elementosRentados : ArrayList ElementoInventario
      - m_contacto : String
      - m_fecha : Date
      + Getters()
      + Setters()
    }

    class Agenda{
      - m_rentas : ArrayList Renta
      + AgregarRecordatorio(rentaNueva : Renta) void
      + EliminarRecordatorio(rentaEliminada : Renta) void
            + Getters()
      + Setters()
    }

    class InventarioRepository{
      <<Interfaz>>
      + ObtenerElementos() ArrayList ElementoInventario
      + GuardarElemento(elementoParaGuardar : ElementoInventario) void
      + EliminarElemento(elementoParaEliminar : ElementoInventario) void
      + EncontrarPorID(AUN NO DECIDADA LA ID) : ElementoInventario
    }

    class InventarioRepositoryImp{
      
    }

    class AgendaRepository{
      <<Interfaz>>
      + ObtenerRentas() ArrayList Renta
      + GuardarRenta(rentaParaGuardar : Renta) void
      + EliminarRenta(rentaParaEliminar : Renta) void
      + EncontrarPorID(AUN NO DECIDADA LA ID) : Renta
    }

    class AgendaRepositoryImp{

    }